name: Python - Lint

on: push

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: flake8-errors
      shell: bash
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pip install flake8==6.1.0
        flake8 . \
          --count \
          --select=E9,F63,F7,F82 \
          --show-source --statistics
    - name: flake8-full
      shell: bash
      run: |
        pip install flake8==6.1.0
        flake8 . \
          --count --statistics \
          --max-line-length=100 \
          --exclude static_feeds.py
    - name: black
      shell: bash
      run: |
        pip install black==23.10.1
        black --diff --check .
