name: Build, Tag & Push Docker image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      is-latest:
        required: false
        type: boolean
        default: false
      pr-number:
        required: false
        type: number
        default: 0
      milestone-number:
        required: false
        type: number
        default: 0

runs:
  using: "composite"
  
  steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      shell: bash
      run: docker build . --file Dockerfile --tag "${{ inputs.image-name }}" --label "runnumber=${GITHUB_RUN_ID}"
    - name: Log in to GitHub Container Registry
      shell: bash
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push Docker image
      shell: bash
      run: |
        IMAGE_ID=ghcr.io/${{ inputs.image-name }}
        # changes all uppercase characters to lowercase:
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        
        # push into main branch is a release to latest
        if [[ ${{ inputs.is-latest }} == true ]]; then
          docker tag ${{ inputs.image-name }} $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
          echo "docker push $IMAGE_ID:latest"
        fi
        
        # each PR has a separate tag: pr-<number>
        if [[ ${{ inputs.pr-number }} != 0 ]]; then
          PR=pr-${{ inputs.pr-number }}
          docker tag ${{ inputs.image-name }} $IMAGE_ID:$PR
          docker push $IMAGE_ID:$PR
          echo "docker push $IMAGE_ID:$PR"
          
          # each PR with a milestone has a separate tag: milestone-<number>
          # is it okay? test it
          if [[ ${{ inputs.milestone-number }} != 0 ]]; then
            MILESTONE=milestone-${{ inputs.milestone-number }}
            docker tag ${{ inputs.image-name }} $IMAGE_ID:$MILESTONE
            docker push $IMAGE_ID:$MILESTONE
            echo "docker push $IMAGE_ID:$MILESTONE"
          fi
        fi
        
        # everything is also pushed to dev
        docker tag ${{ inputs.image-name }} $IMAGE_ID:dev
        docker push $IMAGE_ID:dev
        echo "docker push $IMAGE_ID:dev"
